### ISSUE TITLE
Support RuboCop v1.65.1

### ISSUE THREAD

**Issue by tmimura39** [Shopify/erb_lint#371]
I get the following error when running erblint with RuboCop v1.65.1

```
`require': cannot load such file -- rexml/document (LoadError)
```

This may be due to the removal of rexml from RuboCop's dependencies.
https://github.com/rubocop/rubocop/pull/13165

The following options are available to address this case.

* Add `rexml` to erblint's dependency
* Modify to not use `rexml` as well as RuboCop

how do you like it?

**Comment by etiennebarrie** [comment]
We need rexml (at least optionally) for the [JUnit reporter](https://github.com/Shopify/erb_lint/blob/b17760d7c79654b18a0b91e7988ea634590cd34b/lib/erb_lint/reporters/junit_reporter.rb#L3).

So minimally we could add rexml to the gemspec.

But a better solution IMO would be to use a call to `gem` like [Rails does for database adapters](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L14-L15).

And then making sure we don't load the JUnit reporter unless requested by the configuration.

That way, a project using JUnit would get a proper exception when trying to use it without rexml available either bundled in Ruby or in their application bundle, but projects not using that reporter would not need rexml in their bundle.

**Comment by yxhuvud** [comment]
Would anyone be opposed to adding rexml to the gemspec as a quickfix to get everything clean and green on update everywhere and then do the refactor whenever someone feels like doing it? I guess it lessens the risk that it actually get improved but then extra dependencies that isn't needed is the kind of  thing that people may fix just for the hell of it.
